# AWS S3/CodeDeploy를 통한 CI/CD
# 현재 방식은 프로젝트 그대로 올리는 방식임
# zip 압축 후 올리는 방법으로 변경중
name: Deploy to Production
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-18.04
    env:
        IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
 
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
 
      - name: Install Dependencies
        run: npm install
 
      - name: Build
        run: npm run build
        
      - name: Make zip file
        run: zip -r ./deploy_$IMAGE_TAG.zip .
        shell: bash
      - name: S3 Upload
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET_NAME: my-nest-app-deploy-bucket # S3 버킷 이름
          PROJECT_NAME: main # S3 버킷 내 폴더 이름 임의로 정하면 알아서 만들어줌
          AWS_CODEDEPLOY_APPLICATION_NAME: 5gnun-fleamarket # CodeDeploy 애플리케이션 이름
          AWS_CODEDEPLOY_DEPLOYMENT_GROUP_NAME: 5gnun-fleamarketDeploy # CodeDeploy 배포 그룹 이름
       # run: |
       #   aws s3 cp \
       #     --recursive \
       #     --region ap-northeast-2 \
       #     /home/runner/work/5g-fleamarket/5g-fleamarket s3://5gnunfleamarket-bucket/main
        run: aws deploy push 
         --application-name 5gnun-fleamarket
         --description "5gnunFleaMarket S3 Deploy" 
         --region ap-northeast-2
         --s3-location s3://5gnunfleamarket-bucket/main --source .
            # /home/runner/work/5g-fleamarket/5g-fleamarket/deploy_$IMAGE_TAG.zip 
          

      - name: AWS CodeDeploy
        run: aws deploy create-deployment 
         --application-name 5gnun-fleamarket 
         --deployment-config-name CodeDeployDefault.OneAtATime 
         --deployment-group-name 5gnun-fleamarketDeploy 
         --s3-location bucket=blabla,bundleType=zip,key=deploy_$IMAGE_TAG.zip
