# AWS S3/CodeDeploy를 통한 CI/CD
name: Deploy to Production
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-18.04
    env:
        IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
 
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
 
      - name: Install Dependencies
        run: npm install
 
      - name: Build
        run: npm run build
      - name: configure AWS
        uses: aws-actions/configure-aws-credential@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET_NAME: ${{ serects.S3_BUCKET_NAME }} # S3 버킷 이름
          PROJECT_NAME: main # S3 버킷 내 폴더 이름 임의로 정하면 알아서 만들어줌
          AWS_CODEDEPLOY_APPLICATION_NAME: ${{ serects.AWS_CODEDEPLOY_APPLICATION_NAME }} # CodeDeploy 애플리케이션 이름
          AWS_CODEDEPLOY_DEPLOYMENT_GROUP_NAME: ${{ serects.AWS_CODEDEPLOY_DEPLOYMENT_GROUP_NAME }} # CodeDeploy 배포 그룹 이름
      - name: Make zip file
        run: zip -r ./deploy_$IMAGE_TAG.zip .
        shell: bash
      - name: S3 Upload
        run: aws s3 cp --region ${{ AWS_REGION }} ./$GITHUB_SHA.zip s3://${{ S3_BUCKET_NAME }}/main/$GITHUB_SHA.zip
       # run: |
       #   aws s3 cp \
       #     --recursive \
       #     --region ap-northeast-2 \
       #     /home/runner/work/5g-fleamarket/5g-fleamarket s3://5gnunfleamarket-bucket/main

      - name: S3 Upload
        run: aws deploy push --application-name ${{ AWS_CODEDEPLOY_APPLICATION_NAME }} --description "5gnunfleamarket-deploy" --s3-location s3://${{ S3_BUCKET_NAME }}/deploy_$IMAGE_TAG.zip --source .

      - name: code deploy
        run: aws deploy create-deployment --application-name ${{ AWS_CODEDEPLOY_APPLICATION_NAME }} --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name server --s3-location bucket=${{ S3_BUCKET_NAME }},bundleType=zip,key=deploy_$IMAGE_TAG.zip
